name: quantum_pong
channels:
  - anaconda
  - clinicalgraphics
  - conda-forge

dependencies:
  - python =3.5
  - numpy
  # dev
  - pyyaml =3.11*
  - invoke >=0.12*
  # tests
  - pytest >=2.8.4,<2.9

  - scipy
  - numpy-indexed =0.3*
  - matplotlib >=1.4.3,<1.6
  - anaconda-client >=1.2.1,<1.3
  - pyyaml =3.11*
  - invoke
  # visualize
  - pyopengl
  - imageio
  - pip:    # build vispy from master
    - "--editable=git+https://github.com/vispy/vispy.git#egg=vispy-master"
    - "C:/Users/Eelco/Downloads/pyopencl-2016.1-cp35-cp35m-win_amd64.whl"
